spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/login_sys
    username: login_admin
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  server:
    port: 9091